import ConnectionService from "../services/connectionService";
import { supabase } from "../supabaseClient";

/**
 * Función para asegurar que existe una conexión Power Automate
 * Esto se ejecuta automáticamente al cargar la aplicación
 */
export async function ensurePowerAutomateConnection() {
  try {
    // Verificar si el usuario está autenticado
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return;

    // Verificar si el usuario es admin
    const { data: profile } = await supabase
      .from("profiles")
      .select("role, admin")
      .eq("id", user.id)
      .single();

    const isAdmin = profile?.role === "admin" || profile?.admin === true;
    if (!isAdmin) return; // Solo admins pueden crear conexiones

    // Verificar si ya existe una conexión Power Automate
    const result = await ConnectionService.getUserConnections();
    const hasPowerAutomate = result.connections.some(
      (conn) => conn.type === "powerautomate"
    );

    if (hasPowerAutomate) {
      console.log("Conexión Power Automate ya existe");
      return;
    }

    // Verificar si hay variables de entorno configuradas
    const flowUrl = import.meta.env.VITE_POWERAUTOMATE_GET_URL_SS;
    if (!flowUrl) {
      console.log(
        "No hay configuración de Power Automate en variables de entorno"
      );
      return;
    }

    console.log("Creando conexión Power Automate automáticamente...");

    // Crear conexión con credenciales por defecto
    const connectionData = {
      name: "Power Automate Principal",
      type: "powerautomate",
      description:
        "Conexión principal a Microsoft Power Automate para cupos de vuelo (creada automáticamente)",
      credentials: {
        flowUrl: flowUrl,
        apiKey: "", // Power Automate no usa API key
        postUrl: import.meta.env.VITE_POWERAUTOMATE_POST_URL || "",
      },
    };

    // Usar contraseña por defecto para la encriptación automática
    const defaultPassword = "AutoGeneratedPA2024!"; // Contraseña temporal para auto-creación

    const createResult = await ConnectionService.createConnection(
      connectionData,
      defaultPassword
    );

    if (createResult.success) {
      console.log("✅ Conexión Power Automate creada automáticamente");

      // Activar la conexión automáticamente
      await ConnectionService.setActiveConnection(createResult.connection.id);
      console.log("✅ Conexión Power Automate activada automáticamente");
    } else {
      console.error(
        "❌ Error creando conexión Power Automate:",
        createResult.error
      );
    }
  } catch (error) {
    console.error("Error en ensurePowerAutomateConnection:", error);
  }
}
